---
abstract: 'Perl class for pyx2xml application.'
author:
  - 'Michal Spacek <skim@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.19'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-PYX2XML
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Getopt::Std: 0
  PYX::SGML::Tags: 0.02
  Tags::Output::Indent: 0.04
  Tags::Output::Raw: 0.04
  perl: 5.6.2
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=App-PYX2XML
  homepage: https://github.com/tupinek/App-PYX2XML
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/tupinek/App-PYX2XML
version: '0.03'
